upstream backend {
    server backend:8000;
}

upstream frontend {
    server frontend:80;
}

upstream tg_webapp {
    server tg-webapp:80;
}

upstream tablet {
    server tablet:80;
}

# Main site
server {
    listen 80;
    server_name localhost;

    location /api/v1/ {
        proxy_pass http://backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Telegram web app
server {
    listen 80;
    server_name tg.localhost;

    location /api/v1/ {
        proxy_pass http://backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://tg_webapp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Tablet app
server {
    listen 80;
    server_name app.localhost;

    location /api/v1/ {
        proxy_pass http://backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://tablet;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
